In [1]:
1+1

2

In [2]:
2 * 'abhi'

'abhiabhi'

In [3]:
a=10
b=22
print (a*b)

220


In [7]:
first_name="abhinav"
last_name="singh"
print("my first name is {first} and my last name is {last}".format(last=last_name,first=first_name))

my first name is abhinav and my last name is singh


In [8]:
len('hi there how are you')

20

In [9]:
len([1,2,3,])

3

In [11]:
type(True)

bool

In [28]:
my_str="my"
print(my_str.isupper())
print(my_str.isalnum())

False
True


In [29]:
my_str="my"
print(my_str.isupper())
print(my_str.isalnum())

False
True


In [2]:
str_example="hello world"
my_str="abhi123"
my_str.isalnum() and str_example.isalpha()

False

In [4]:
type([])

list

In [6]:
pip install jupyterthemes

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
print("hello world")

hello world


In [2]:
set_var={1,2,3,4,5,1,2,7,8,9,66,5,3} #curly bracket
set_var

{1, 2, 3, 4, 5, 7, 8, 9, 66}

In [14]:
set1={'abhi' ,'shubh' , 'sakku' , 'nandu'}
set2={'abhi' , 'shubh' , 'nandu'}
set1.difference_update(set2) 
print(set1)

{'sakku'}


In [13]:
print(set2)

{'nandu', 'abhi', 'shubh'}


In [15]:
import numpy as np

In [16]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr.shape #this is how 1-d array represented

(5,)

In [22]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

arr=np.array([my_list1,my_list2,my_list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
arr.shape

(3, 5)

In [24]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 15 into shape (5,2)

In [3]:
arr=np.arrange[1,2,3,4,5,6,7,8,9]

NameError: name 'np' is not defined

In [2]:
arr

NameError: name 'arr' is not defined

In [4]:
import pandas as pd
import numpy as np

In [13]:
 df=pd.DataFrame(np.arrange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2,'Column3','Column4'])

SyntaxError: unterminated string literal (detected at line 1) (1683754270.py, line 1)

In [10]:
data = np.arange(0, 20).reshape(5, 4)
df = pd.DataFrame(data, index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Column1', 'Column2', 'Column3', 'Column4'])


In [12]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [16]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4) , index=['Row1','Row2','Row3','Row4','Row5'] , columns=['Column1','Column2','Column3','Column4'])

In [17]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19