### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [20]:
import numpy as np
import random

In [29]:
arr= np.random.randint(1,21,size=(5,5))
print(arr)

arr[: , 2] =  1
print(arr)

[[ 7 18 18  4  1]
 [14 16  8 15  8]
 [ 8  1 12 16  2]
 [11 16  8  4  6]
 [17 14  6 16  2]]
[[ 7 18  1  4  1]
 [14 16  1 15  8]
 [ 8  1  1 16  2]
 [11 16  1  4  6]
 [17 14  1 16  2]]


In [11]:
arr1 = np.arange(1,17).reshape(4,4)
print('Original Array')
print(arr1)

diagonal_arr = np.fill_diagonal(arr1,0)
print('Modified Array')
print(arr1)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [19]:
arr = np.arange(1,37).reshape(6,6)
print('Original Array')
print(arr)

sub_array1 = arr[2:5 ,1:3]
print("Sub Array is")
print(sub_array1)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array is
[[14 15]
 [20 21]
 [26 27]]


In [45]:
arr = np.random.randint(1,100,size=(5,5))
print(arr)

border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1 , 0] , arr[1:-1 , -1]))
print(border_elements)

[[67 16  5 19 10]
 [57 32 75 92 74]
 [85 63 10 96 18]
 [ 4 26 48 13 27]
 [ 4 93 81 49 13]]
[67 16  5 19 10  4 93 81 49 13 57 85  4 74 18 27]
