### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np
import random

In [3]:
arr= np.random.randint(1,21,size=(5,5))
print(arr)

arr[: , 2] =  1
print(arr)

[[17  5  2 10  5]
 [ 4  5  7 12 18]
 [18  1  1  5  5]
 [ 3  5  8 12 14]
 [ 4  2  4  9 16]]
[[17  5  1 10  5]
 [ 4  5  1 12 18]
 [18  1  1  5  5]
 [ 3  5  1 12 14]
 [ 4  2  1  9 16]]


In [4]:
arr1 = np.arange(1,17).reshape(4,4)
print('Original Array')
print(arr1)

diagonal_arr = np.fill_diagonal(arr1,0)
print('Modified Array')
print(arr1)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr = np.arange(1,37).reshape(6,6)
print('Original Array')
print(arr)

sub_array1 = arr[2:5 ,1:3]
print("Sub Array is")
print(sub_array1)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array is
[[14 15]
 [20 21]
 [26 27]]


In [6]:
arr = np.random.randint(1,100,size=(5,5))
print(arr)

border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1 , 0] , arr[1:-1 , -1]))
print(border_elements)

[[47 52 86 74 38]
 [65  8 65 59 69]
 [10 36 11 62 76]
 [69 80 35 53 16]
 [62  5 53 45 43]]
[47 52 86 74 38 62  5 53 45 43 65 10 69 69 76 16]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr1 = np.random.randint(1,100,size = (3,4))
arr2 = np.random.randint(1,100,size = (3,4))
print("Array 1 :")
print(arr1)
print("Array 2 :")
print(arr2)
print("Addition")
print(arr1 + arr2)
print("Subtraction")
print(arr1 - arr2)
print("Multiplication")
print(arr1 * arr2)
print("Division")
print(arr1 / arr2)


Array 1 :
[[71 49 69 37]
 [59 18 30 39]
 [50 18 57 55]]
Array 2 :
[[96  5 62 31]
 [ 4 68 22 95]
 [83 72 22 30]]
Addition
[[167  54 131  68]
 [ 63  86  52 134]
 [133  90  79  85]]
Subtraction
[[-25  44   7   6]
 [ 55 -50   8 -56]
 [-33 -54  35  25]]
Multiplication
[[6816  245 4278 1147]
 [ 236 1224  660 3705]
 [4150 1296 1254 1650]]
Division
[[ 0.73958333  9.8         1.11290323  1.19354839]
 [14.75        0.26470588  1.36363636  0.41052632]
 [ 0.60240964  0.25        2.59090909  1.83333333]]


In [8]:
arr = np.arange(1,17).reshape(4,4)
Coloum_wise_Sum = np.sum(arr, axis = 0)
row_wise_sum = np.sum(arr , axis = 1)

print("The Array is:\n", arr)
print("Row wise Addition is\n",row_wise_sum)
print("Coloumn wise Addition is\n",Coloum_wise_Sum)

The Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise Addition is
 [10 26 42 58]
Coloumn wise Addition is
 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr = np.random.randint(1,25,size=(5,5))
mean = np.mean(arr)
median = np.median(arr)
Standard_Variance = np.var(arr)

print("Array:\n" , arr)
print("Mean:\n" , mean)
print("Median:\n" , median)
print("Standard Variance:\n" , Standard_Variance)

Array:
 [[14 12 10 19  1]
 [ 2 24 12 17 24]
 [17  6 24  6 16]
 [21  1  7 16 22]
 [ 1 19 12  5 21]]
Mean:
 13.16
Median:
 14.0
Standard Variance:
 58.2944


In [10]:
arr = np.arange(1,10).reshape(3,3)
print("The array is\n" , arr)

mean = np.mean(arr)
std_dev  = np.std(arr)
normalised_arr = (arr - mean) / std_dev

print("Normalised Array is\n" , normalised_arr)

The array is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalised Array is
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [11]:
arr2D = np.random.randint(1, 11, size=(3, 3))
arr1D = np.random.randint(1, 11, size=(3,))

addition = arr2D + arr1D
print("2D Array:\n", arr2D)
print("1D Array:\n", arr1D)
print("Result of Addition:\n", addition)

2D Array:
 [[5 6 7]
 [7 2 6]
 [9 5 7]]
1D Array:
 [8 9 2]
Result of Addition:
 [[13 15  9]
 [15 11  8]
 [17 14  9]]


In [12]:
arr2D = np.random.randint(1, 11, size=(4, 4))
arr1D = np.random.randint(1, 11, size=(4,))

addition = arr2D - arr1D
print("2D Array:\n", arr2D)
print("1D Array:\n", arr1D)
print("Result of Subtraction:\n", addition)

2D Array:
 [[ 2  5  6  6]
 [10  8  3  8]
 [ 2  6 10 10]
 [ 9  7  5  3]]
1D Array:
 [5 3 7 4]
Result of Subtraction:
 [[-3  2 -1  2]
 [ 5  5 -4  4]
 [-3  3  3  6]
 [ 4  4 -2 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
matrix = np.arange(1,18,2).reshape(3,3)
Determinant = np.linalg.det(matrix)
Inverse = np.linalg.inv(matrix)
Eigenvalues = np.linalg.eigvals(matrix)

print("The Matrix is\n" , matrix)
print("The Determinant is\n" , Determinant)
print("The Inverse is\n" , Inverse)
print("The Eigenvalues is\n" , Eigenvalues)

The Matrix is
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
The Determinant is
 4.263256414560604e-14
The Inverse is
 [[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]
The Eigenvalues is
 [ 2.94452187e+01 -2.44521872e+00 -1.61086274e-15]


In [18]:
matrix1 = np.arange(1,7).reshape(2,3)
matrix2 = np.arange(1,7).reshape(3,2)

multiplication = np.linalg.matmul(matrix1,matrix2)
print("Matrix1 :\n" , matrix1)
print("Matrix2 :\n" , matrix2)
print("Multiplication of matrix is \n" , multiplication)


Matrix1 :
 [[1 2 3]
 [4 5 6]]
Matrix2 :
 [[1 2]
 [3 4]
 [5 6]]
Multiplication of matrix is 
 [[22 28]
 [49 64]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [20]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr.reshape(1,9)
arr2 = arr1.reshape(9,1)

print("Main array is\n" , arr)
print("first Manupulated array is\n" , arr1)
print("Second Manupulation is \n" , arr2)

Main array is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
first Manupulated array is
 [[1 2 3 4 5 6 7 8 9]]
Second Manupulation is 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [24]:
arr = np.random.randint(1,26,size = (5,5))
print("Array is\n" , arr)
flatten_arr = arr.flatten()
print("Flattened array is\n" , flatten_arr)
reshape_arr = flatten_arr.reshape(5,5)
print("Reshaped Array is\n" , reshape_arr)

Array is
 [[ 4 21 12 18 16]
 [ 8  7 17 12  4]
 [21 18 24 20 25]
 [ 2 20 17 11 10]
 [25 24 20 24 15]]
Flattened array is
 [ 4 21 12 18 16  8  7 17 12  4 21 18 24 20 25  2 20 17 11 10 25 24 20 24
 15]
Reshaped Array is
 [[ 4 21 12 18 16]
 [ 8  7 17 12  4]
 [21 18 24 20 25]
 [ 2 20 17 11 10]
 [25 24 20 24 15]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 

In [31]:
arr = np.random.randint(1,100,size=(5,5))
fancy_Indexing = arr[[0,0,-1,-1],[0,-1,0,-1]] #i9f you use () , the object is not callable
print("Array is\n" , arr)
print("Corners are\n" , fancy_Indexing)

Array is
 [[72 38 24  2 43]
 [77 62 78 81 39]
 [14 94 52 79 57]
 [72 29 99 11 25]
 [33 46 38 36 75]]
Corners are
 [72 43 33 75]


In [41]:
arr = np.random.randint(1,30,size=(4,4))
boolean_Indexing = arr[arr>10]
print("Array is\n" , arr)
print("required value is\n", boolean_Indexing)

Array is
 [[24 11  7  8]
 [ 1 10  6  6]
 [ 6 18  3 15]
 [27 15 16 15]]
required value is
 [24 11 18 15 27 15 16 15]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [57]:
data_type = [('name' , 'U10') , ('age' , 'i4') , ('weight' , 'f8')]
arr = np.array([('Abhi' , 20 , 61.5 ) , ('Shubh',19,66.5)], dtype=data_type)
sorted_array = np.sort(arr , order='age')
print('Data\n',arr)
print('Sorted Data\n' , sorted_array)

Data
 [('Abhi', 20, 61.5) ('Shubh', 19, 66.5)]
Sorted Data
 [('Shubh', 19, 66.5) ('Abhi', 20, 61.5)]


### Explanation of Each Field:

#### `('name', 'U10')`:
- **`'name'`**: This is the field name.
- **`'U10'`**: This indicates a Unicode string of up to 10 characters. It can store any string with a maximum length of 10 characters.

#### `('integer', 'i2')`:
- **`'integer'`**: This is the field name.
- **`'i2'`**: This represents a 16-bit signed integer (2 bytes). It can hold integer values in the range of `-32,768` to `32,767`.

#### `('weight', 'f8')`:
- **`'weight'`**: This is the field name.
- **`'f8'`**: This represents a 64-bit floating-point number (8 bytes). It is equivalent to a double precision floating-point number and is used for values that require more precision.


In [59]:
data_type = [('x' , 'i4') , ('y' , 'i4')]
data = np.array([(12,13) , (14,15) , (23,24)] , dtype=data_type)
Euclidean_Distance = np.sqrt()