### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

# create array using numpy
# Create 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row & 5 coloums

array([[1, 2, 3, 4, 5]])

In [4]:
arr3 = np.array([[5,6,7,8]])
arr3.shape

(1, 4)

In [7]:
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1) # elements between 0 to 10 and a step of 2 means every second element is skipped

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4)) # array with 3 rows and 4 coloums and each element is one
               # useful in initilisation

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# identitiy Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Attributes of Numpy
arr5  = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr5)
print("Shape:\n",arr5.shape)
print("Number of Dimentions:",arr5.ndim)
print("Data Type:" , arr5.dtype)
print("item size (in bytes):" , arr5.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of Dimentions: 2
Data Type: int64
item size (in bytes): 8


In [14]:
# Numpy Vectorised operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition:" , arr1+arr2)

# Element wise Subtraction
print("Subtraction:" , arr2 - arr1)

# Element wise Multiplication
print("Subtraction:" , arr2  * arr1)

# Element wise Division
print("Division:" , arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Subtraction: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
# Universal functions
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
arr[0][0]
print(arr[0:2,2:])


[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [32]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [33]:
# Statistical concept -- Normalisation
# have a mean of 0 and a standard deviation of 1
data = np.array([1,2,3,4,5,6])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalise the data
normalised_data = (data-mean) / std_dev
print("Normalised Data", normalised_data)

Normalised Data [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [36]:
# mean , median ,standard deviation , variance

data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("Mean:" , mean)

median = np.median(data)
print("Median:" , mean)

Std_Dev = np.std(data)
print("Standard Deviation:" , Std_Dev)

mean = np.var(data)
print("Variance:" , mean)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [38]:
# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5
data[data>5]

array([ 6,  7,  8,  9, 10])

In [41]:
data[(data>6) & (data<6)]

array([], dtype=int64)